### ISSUE TITLE
Dutch translation added

### ISSUE THREAD

**Issue by rvanc** [Anteater46/ModTranslations#2]
Not entirely sure if there is perhaps a better Dutch word for the flour paste. The word paste in Dutch is also used for 'pasta', so if that one is used it would sound as if the item is 'wheat pasta', instead I used the dutch word for glue, as flour paste is often used in paper mache projects. 

[nl_nl.zip](https://github.com/Anteater46/ModTranslations/files/5000910/nl_nl.zip)

**Comment by Anteater46** [comment]
Thanks for doing this! Glue works :)
