### ISSUE TITLE
Translation: Portuguese.

### ISSUE THREAD

**Issue by F35H** [Anteater46/ModTranslations#3]
Brazilian Portuguese

{
  "item.flourpower.flour":"Farinha de trigo",
  "item.flourpower.flour_paste":"Pasta de farinha de trigo",
  "item.flourpower.smoked_bread": "Pão defumado",

  "tooltip.flourpaste.0":"Pode agir como bola de slime.",
  "tooltip.smokedbread.0": "É perfeito com manteiga de bordo."
}

Continental [European] Portuguese

{
  "item.flourpower.flour":"Farinha de trigo",
  "item.flourpower.flour_paste":"Pasta de farinha de trigo",
  "item.flourpower.smoked_bread": "Pão fumado",

  "tooltip.flourpaste.0":"Pode agir como bola de slime.",
  "tooltip.smokedbread.0": "É perfeito com manteiga de bordo."
}

**Comment by Anteater46** [comment]
Thanks! This will be in the next version :)

**Comment by F35H** [comment]
Yeah, if you need any other translations, contact me. Thanks!
