### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by EinKlumpenZucker** [Anteater46/ModTranslations#4]
{
  "item.flourpower.flour":"Mehl",
  "item.flourpower.flour_paste":"Mehlkleister",
  "item.flourpower.smoked_bread": "Räucherbrot",

  "tooltip.flourpaste.0":"Kann als Schleimball verwendet werden.",
  "tooltip.smokedbread.0": "Perfekt mit Ahorncreme!"
}

**Comment by Anteater46** [comment]
Thanks for this! It'll be in the next version of FP :)
